import { Question, PYQQuestion } from '../types';

export const COMPREHENSIVE_QUESTIONS: Question[] = [
  // --- PHYSICS ---
  {
    id: 101,
    subject: 'Physics',
    chapter_name_en: 'Electric Charges and Fields',
    chapter_name_hi: 'वैद्युत आवेश तथा क्षेत्र',
    question_text_en: 'The SI unit of electric flux is:',
    question_text_hi: 'विद्युत फ्लक्स का SI मात्रक है:',
    option_a_en: 'Weber',
    option_a_hi: 'वेबर',
    option_b_en: 'Nm²C⁻¹ / V·m',
    option_b_hi: 'Nm²C⁻¹ / V·m',
    option_c_en: 'Newton',
    option_c_hi: 'न्यूटन',
    option_d_en: 'Volt',
    option_d_hi: 'वोल्ट',
    correct_option: 'B',
    solution_short_en: 'Electric flux Φ = E.A = (N/C) * m² = V·m or Nm²C⁻¹.',
    solution_short_hi: 'विद्युत फ्लक्स Φ = E.A = (N/C) * m² = V·m या Nm²C⁻¹.',
    exam_year: '2021A'
  },
  {
    id: 102,
    subject: 'Physics',
    chapter_name_en: 'Electric Charges and Fields',
    chapter_name_hi: 'वैद्युत आवेश तथा क्षेत्र',
    question_text_en: 'The value of 1/(4πε₀) is:',
    question_text_hi: '1/(4πε₀) का मान होता है:',
    option_a_en: '9 × 10⁹ N m² C⁻²',
    option_a_hi: '9 × 10⁹ N m² C⁻²',
    option_b_en: '9 × 10⁻⁹ N m² C⁻²',
    option_b_hi: '9 × 10⁻⁹ N m² C⁻²',
    option_c_en: '8.85 × 10⁻¹² C² N⁻¹ m⁻²',
    option_c_hi: '8.85 × 10⁻¹² C² N⁻¹ m⁻²',
    option_d_en: '1.6 × 10⁻¹⁹ C',
    option_d_hi: '1.6 × 10⁻¹⁹ C',
    correct_option: 'A',
    solution_short_en: '1/(4πε₀) = 8.987 × 10⁹ ≈ 9 × 10⁹ N m² C⁻².',
    solution_short_hi: '1/(4πε₀) का मान लगभग 9 × 10⁹ N m² C⁻² होता है।',
    exam_year: '2022A'
  },
  {
    id: 103,
    subject: 'Physics',
    chapter_name_en: 'Electric Charges and Fields',
    chapter_name_hi: 'वैद्युत आवेश तथा क्षेत्र',
    question_text_en: 'The electric dipole moment vector has a direction from:',
    question_text_hi: 'विद्युत द्विध्रुव आघूर्ण की दिशा होती है:',
    option_a_en: 'Negative charge to positive charge',
    option_a_hi: 'ऋण आवेश से धन आवेश की ओर',
    option_b_en: 'Positive charge to negative charge',
    option_b_hi: 'धन आवेश से ऋण आवेश की ओर',
    option_c_en: 'Perpendicular to the line joining them',
    option_c_hi: 'दोनों को मिलाने वाली रेखा के लंबवत',
    option_d_en: 'Random direction',
    option_d_hi: 'यादृच्छिक दिशा में',
    correct_option: 'A',
    solution_short_en: 'By convention, electric dipole moment p = q * 2a points from -q to +q.',
    solution_short_hi: 'परिपाटी के अनुसार विद्युत द्विध्रुव आघूर्ण की दिशा ऋण आवेश से धन आवेश की ओर होती है।',
    exam_year: '2023A'
  },
  {
    id: 104,
    subject: 'Physics',
    chapter_name_en: 'Electrostatic Potential and Capacitance',
    chapter_name_hi: 'स्थिरवैद्युत विभव तथा धारिता',
    question_text_en: 'The unit of capacitance is:',
    question_text_hi: 'धारिता का मात्रक होता है:',
    option_a_en: 'Volt',
    option_a_hi: 'वोल्ट',
    option_b_en: 'Farad',
    option_b_hi: 'फैराड',
    option_c_en: 'Coulomb',
    option_c_hi: 'कूलॉम',
    option_d_en: 'Ohm',
    option_d_hi: 'ओम',
    correct_option: 'B',
    solution_short_en: 'Capacitance C = Q/V, its SI unit is Farad (Coulomb/Volt).',
    solution_short_hi: 'धारिता का मात्रक फैराड (F = C/V) होता है।',
    exam_year: '2020A'
  },
  {
    id: 105,
    subject: 'Physics',
    chapter_name_en: 'Electrostatic Potential and Capacitance',
    chapter_name_hi: 'स्थिरवैद्युत विभव तथा धारिता',
    question_text_en: 'Energy stored in a capacitor of capacitance C and voltage V is:',
    question_text_hi: 'धारिता C और विभव V वाले संधारित्र की संचित ऊर्जा होती है:',
    option_a_en: '1/2 CV²',
    option_a_hi: '1/2 CV²',
    option_b_en: '1/2 C²V',
    option_b_hi: '1/2 C²V',
    option_c_en: 'CV²',
    option_c_hi: 'CV²',
    option_d_en: '1/2 (C/V)',
    option_d_hi: '1/2 (C/V)',
    correct_option: 'A',
    solution_short_en: 'Energy U = 1/2 CV² = Q² / (2C) = 1/2 QV.',
    solution_short_hi: 'संधारित्र की संचित स्थितिज ऊर्जा U = 1/2 CV² होती है।',
    exam_year: '2021A'
  },
  {
    id: 106,
    subject: 'Physics',
    chapter_name_en: 'Current Electricity',
    chapter_name_hi: 'विद्युत धारा',
    question_text_en: 'Kirchhoff’s current law (junction rule) is based on conservation of:',
    question_text_hi: 'किरचॉफ का धारा नियम (संधि नियम) किस संरक्षण पर आधारित है?',
    option_a_en: 'Energy',
    option_a_hi: 'ऊर्जा',
    option_b_en: 'Charge',
    option_b_hi: 'आवेश',
    option_c_en: 'Momentum',
    option_c_hi: 'संवेग',
    option_d_en: 'Mass',
    option_d_hi: 'द्रव्यमान',
    correct_option: 'B',
    solution_short_en: 'Junction law is based on charge conservation. Loop law is based on energy conservation.',
    solution_short_hi: 'किरचॉफ का प्रथम नियम (संधि नियम) आवेश संरक्षण के नियम पर आधारित है।',
    exam_year: '2022A'
  },
  {
    id: 107,
    subject: 'Physics',
    chapter_name_en: 'Current Electricity',
    chapter_name_hi: 'विद्युत धारा',
    question_text_en: 'Which instrument is used to measure potential difference without drawing current?',
    question_text_hi: 'परिपथ से बिना धारा लिए विभवांतर मापने के लिए कौन सा उपकरण उपयुक्त है?',
    option_a_en: 'Voltmeter',
    option_a_hi: 'वोल्टमीटर',
    option_b_en: 'Potentiometer',
    option_b_hi: 'विभवमापी',
    option_c_en: 'Ammeter',
    option_c_hi: 'अमीटर',
    option_d_en: 'Galvanometer',
    option_d_hi: 'गैल्वेनोमीटर',
    correct_option: 'B',
    solution_short_en: 'A potentiometer works on null deflection method, drawing zero current at balance.',
    solution_short_hi: 'विभवमापी शून्य विक्षेप विधि पर कार्य करता है, अतः यह आदर्श उपकरण माना जाता है।',
    exam_year: '2023A'
  },
  {
    id: 108,
    subject: 'Physics',
    chapter_name_en: 'Moving Charges and Magnetism',
    chapter_name_hi: 'गतिमान आवेश और चुंबकत्व',
    question_text_en: 'The SI unit of magnetic field (B) is:',
    question_text_hi: 'चुंबकीय क्षेत्र (B) का SI मात्रक है:',
    option_a_en: 'Tesla (T)',
    option_a_hi: 'टेस्ला (T)',
    option_b_en: 'Weber (Wb)',
    option_b_hi: 'वेबर (Wb)',
    option_c_en: 'Henry (H)',
    option_c_hi: 'हेनरी (H)',
    option_d_en: 'Ampere/meter',
    option_d_hi: 'एम्पीयर/मीटर',
    correct_option: 'A',
    solution_short_en: 'Magnetic field intensity B has SI unit Tesla (T) or Wb/m².',
    solution_short_hi: 'चुंबकीय क्षेत्र का SI मात्रक टेस्ला (Tesla) या वेबर/मीटर² होता है।',
    exam_year: '2024A'
  },
  {
    id: 109,
    subject: 'Physics',
    chapter_name_en: 'Ray Optics and Optical Instruments',
    chapter_name_hi: 'किरण प्रकाशिकी एवं प्रकाशिक यंत्र',
    question_text_en: 'The optical fiber works on the principle of:',
    question_text_hi: 'प्रकाशिक तंतु (Optical Fiber) किस सिद्धांत पर कार्य करता है?',
    option_a_en: 'Total Internal Reflection',
    option_a_hi: 'पूर्ण आंतरिक परावर्तन',
    option_b_en: 'Refraction',
    option_b_hi: 'अपवर्तन',
    option_c_en: 'Dispersion',
    option_c_hi: 'वर्ण-विक्षेपण',
    option_d_en: 'Diffraction',
    option_d_hi: 'विवर्तन',
    correct_option: 'A',
    solution_short_en: 'Light in optical fiber travels via repeated total internal reflections (TIR).',
    solution_short_hi: 'ऑप्टिकल फाइबर पूर्ण आंतरिक परावर्तन (Total Internal Reflection) के सिद्धांत पर कार्य करता है।',
    exam_year: '2022A'
  },
  {
    id: 110,
    subject: 'Physics',
    chapter_name_en: 'Semiconductor Electronics',
    chapter_name_hi: 'अर्धचालक इलेक्ट्रॉनिकी',
    question_text_en: 'In an intrinsic semiconductor at absolute zero temperature (0 K), it behaves as:',
    question_text_hi: 'परम शून्य ताप (0 K) पर शुद्ध अर्धचालक किसकी तरह व्यवहार करता है?',
    option_a_en: 'Conductor',
    option_a_hi: 'सुचालक',
    option_b_en: 'Insulator',
    option_b_hi: 'कुचालक',
    option_c_en: 'Superconductor',
    option_c_hi: 'अतिचालक',
    option_d_en: 'Semi-metal',
    option_d_hi: 'अर्धधातु',
    correct_option: 'B',
    solution_short_en: 'At 0 K, no valence electrons have thermal energy to jump to conduction band.',
    solution_short_hi: '0 K पर सभी सहसंयोजक बंध पूर्ण होते हैं, अतः यह आदर्श कुचालक (अचालक) की तरह व्यवहार करता है।',
    exam_year: '2023A'
  },

  // --- CHEMISTRY ---
  {
    id: 201,
    subject: 'Chemistry',
    chapter_name_en: 'Solutions',
    chapter_name_hi: 'विलयन',
    question_text_en: 'Which of the following concentration terms is independent of temperature?',
    question_text_hi: 'निम्नलिखित में से कौन सी सांद्रता इकाई ताप पर निर्भर नहीं करती है?',
    option_a_en: 'Molality (m)',
    option_a_hi: 'मोललता (m)',
    option_b_en: 'Molarity (M)',
    option_b_hi: 'मोलरता (M)',
    option_c_en: 'Normality (N)',
    option_c_hi: 'नॉर्मलता (N)',
    option_d_en: 'Formality',
    option_d_hi: 'फॉर्मलता',
    correct_option: 'A',
    solution_short_en: 'Molality is moles of solute per kg of solvent (mass based), so temperature independent.',
    solution_short_hi: 'मोललता विलायक के द्रव्यमान पर आधारित होती है, इसलिए यह ताप पर निर्भर नहीं करती।',
    exam_year: '2021A'
  },
  {
    id: 202,
    subject: 'Chemistry',
    chapter_name_en: 'Solutions',
    chapter_name_hi: 'विलयन',
    question_text_en: 'Colligative properties of a solution depend upon:',
    question_text_hi: 'विलयन के अणुसंख्य गुणधर्म किस पर निर्भर करते हैं?',
    option_a_en: 'Number of solute particles',
    option_a_hi: 'विलेय के कणों की संख्या पर',
    option_b_en: 'Nature of solute particles',
    option_b_hi: 'विलेय के कणों की प्रकृति पर',
    option_c_en: 'Nature of solvent',
    option_c_hi: 'विलायक की प्रकृति पर',
    option_d_en: 'Volume of container',
    option_d_hi: 'पात्र के आयतन पर',
    correct_option: 'A',
    solution_short_en: 'Colligative properties depend only on number of solute particles, not their chemical nature.',
    solution_short_hi: 'अणुसंख्य गुणधर्म केवल विलेय कणों की संख्या पर निर्भर करते हैं, उनकी प्रकृति पर नहीं।',
    exam_year: '2022A'
  },
  {
    id: 203,
    subject: 'Chemistry',
    chapter_name_en: 'Electrochemistry',
    chapter_name_hi: 'वैद्युतरसायन',
    question_text_en: 'Faraday’s first law of electrolysis is represented by:',
    question_text_hi: 'फैराडे का विद्युत अपघटन का प्रथम नियम है:',
    option_a_en: 'm = Z · I · t',
    option_a_hi: 'm = Z · I · t',
    option_b_en: 'E = mc²',
    option_b_hi: 'E = mc²',
    option_c_en: 'V = IR',
    option_c_hi: 'V = IR',
    option_d_en: 'm = Q / Z',
    option_d_hi: 'm = Q / Z',
    correct_option: 'A',
    solution_short_en: 'Mass deposited m = Z * Q = Z * I * t, where Z is electrochemical equivalent.',
    solution_short_hi: 'फैराडे के प्रथम नियमानुसार निक्षेपित द्रव्यमान m = Z·I·t होता है।',
    exam_year: '2020A'
  },
  {
    id: 204,
    subject: 'Chemistry',
    chapter_name_en: 'Chemical Kinetics',
    chapter_name_hi: 'रासायनिक बलगतिकी',
    question_text_en: 'The unit of rate constant for a first order reaction is:',
    question_text_hi: 'प्रथम कोटि की अभिक्रिया के लिए वेग स्थिरांक की इकाई होती है:',
    option_a_en: 's⁻¹ (time⁻¹)',
    option_a_hi: 's⁻¹ (समय⁻¹)',
    option_b_en: 'mol L⁻¹ s⁻¹',
    option_b_hi: 'mol L⁻¹ s⁻¹',
    option_c_en: 'L mol⁻¹ s⁻¹',
    option_c_hi: 'L mol⁻¹ s⁻¹',
    option_d_en: 'L² mol⁻² s⁻¹',
    option_d_hi: 'L² mol⁻² s⁻¹',
    correct_option: 'A',
    solution_short_en: 'For order n: (mol/L)^(1-n) * s^-1. For n=1, unit is s^-1.',
    solution_short_hi: 'प्रथम कोटि अभिक्रिया के लिए k की इकाई s⁻¹ (प्रति सेकंड) होती है।',
    exam_year: '2023A'
  },
  {
    id: 205,
    subject: 'Chemistry',
    chapter_name_en: 'Coordination Compounds',
    chapter_name_hi: 'उपसहसंयोजन यौगिक',
    question_text_en: 'The oxidation state of nickel in Ni(CO)₄ is:',
    question_text_hi: 'Ni(CO)₄ में निकेल (Ni) की ऑक्सीकरण संख्या है:',
    option_a_en: '0',
    option_a_hi: '0',
    option_b_en: '+2',
    option_b_hi: '+2',
    option_c_en: '+4',
    option_c_hi: '+4',
    option_d_en: '-2',
    option_d_hi: '-2',
    correct_option: 'A',
    solution_short_en: 'CO is a neutral ligand (charge 0), hence oxidation state of Ni is 0.',
    solution_short_hi: 'CO एक उदासीन लिगैंड है, अतः Ni की ऑक्सीकरण अवस्था शून्य (0) होती है।',
    exam_year: '2024A'
  },
  {
    id: 206,
    subject: 'Chemistry',
    chapter_name_en: 'Haloalkanes and Haloarenes',
    chapter_name_hi: 'हैलोएल्केन तथा हैलोएरीन',
    question_text_en: 'Haloalkanes react with alcoholic KCN to give predominantly:',
    question_text_hi: 'हैलोएल्केन एल्कोहॉलिक KCN के साथ अभिक्रिया करके मुख्य रूप से क्या बनाते हैं?',
    option_a_en: 'Alkyl cyanide (Nitrile)',
    option_a_hi: 'एल्किल सायनाइड (नाइट्राइल)',
    option_b_en: 'Alkyl isocyanide',
    option_b_hi: 'एल्किल आइसोसायनाइड',
    option_c_en: 'Alkane',
    option_c_hi: 'एल्केन',
    option_d_en: 'Alcohol',
    option_d_hi: 'एल्कोहॉल',
    correct_option: 'A',
    solution_short_en: 'KCN is predominantly ionic yielding C-attack (cyanide). AgCN gives isocyanide.',
    solution_short_hi: 'KCN आयनिक होने के कारण कार्बन से जुड़ता है और मुख्य उत्पाद एल्किल सायनाइड बनता है।',
    exam_year: '2022A'
  },

  // --- MATHS ---
  {
    id: 301,
    subject: 'Maths',
    chapter_name_en: 'Matrices',
    chapter_name_hi: 'आव्यूह',
    question_text_en: 'If A is a square matrix, then (A + Aᵀ) is always a:',
    question_text_hi: 'यदि A एक वर्ग आव्यूह है, तो (A + Aᵀ) सदैव होगा:',
    option_a_en: 'Symmetric matrix',
    option_a_hi: 'सममित आव्यूह',
    option_b_en: 'Skew-symmetric matrix',
    option_b_hi: 'विषम-सममित आव्यूह',
    option_c_en: 'Identity matrix',
    option_c_hi: 'तत्समक आव्यूह',
    option_d_en: 'Zero matrix',
    option_d_hi: 'शून्य आव्यूह',
    correct_option: 'A',
    solution_short_en: '(A + Aᵀ)ᵀ = Aᵀ + (Aᵀ)ᵀ = Aᵀ + A = (A + Aᵀ), hence symmetric.',
    solution_short_hi: '(A + Aᵀ) का परिवर्त (A + Aᵀ) ही होता है, अतः यह सदैव सममित आव्यूह होता है।',
    exam_year: '2022A'
  },
  {
    id: 302,
    subject: 'Maths',
    chapter_name_en: 'Determinants',
    chapter_name_hi: 'सारणिक',
    question_text_en: 'If any two rows or columns of a determinant are identical, its value is:',
    question_text_hi: 'यदि किसी सारणिक की कोई दो पंक्तियाँ या दो स्तंभ समान हों, तो उसका मान होगा:',
    option_a_en: '0',
    option_a_hi: '0',
    option_b_en: '1',
    option_b_hi: '1',
    option_c_en: '-1',
    option_c_hi: '-1',
    option_d_en: '2',
    option_d_hi: '2',
    correct_option: 'A',
    solution_short_en: 'Standard property of determinants: identical parallel lines give |A| = 0.',
    solution_short_hi: 'सारणिक के गुणधर्म के अनुसार दो समान पंक्तियों या स्तंभों पर सारणिक का मान शून्य (0) होता है।',
    exam_year: '2021A'
  },
  {
    id: 303,
    subject: 'Maths',
    chapter_name_en: 'Continuity and Differentiability',
    chapter_name_hi: 'सांतत्य तथा अवकलनीयता',
    question_text_en: 'The derivative d/dx (sin⁻¹x) with respect to x is:',
    question_text_hi: 'x के सापेक्ष sin⁻¹x का अवकलज d/dx (sin⁻¹x) है:',
    option_a_en: '1 / √(1 - x²)',
    option_a_hi: '1 / √(1 - x²)',
    option_b_en: '-1 / √(1 - x²)',
    option_b_hi: '-1 / √(1 - x²)',
    option_c_en: '1 / (1 + x²)',
    option_c_hi: '1 / (1 + x²)',
    option_d_en: '1 / (x² - 1)',
    option_d_hi: '1 / (x² - 1)',
    correct_option: 'A',
    solution_short_en: 'Standard calculus identity: d/dx(sin⁻¹x) = 1/√(1 - x²) for |x| < 1.',
    solution_short_hi: 'd/dx (sin⁻¹x) = 1 / √(1 - x²) मानक अवकलन सूत्र है।',
    exam_year: '2023A'
  },
  {
    id: 304,
    subject: 'Maths',
    chapter_name_en: 'Integrals',
    chapter_name_hi: 'समाकलन',
    question_text_en: 'The value of ∫ eˣ dx is:',
    question_text_hi: '∫ eˣ dx का मान है:',
    option_a_en: 'eˣ + C',
    option_a_hi: 'eˣ + C',
    option_b_en: 'e⁻ˣ + C',
    option_b_hi: 'e⁻ˣ + C',
    option_c_en: 'x·eˣ + C',
    option_c_hi: 'x·eˣ + C',
    option_d_en: 'ln(x) + C',
    option_d_hi: 'ln(x) + C',
    correct_option: 'A',
    solution_short_en: 'Integral of exponential function eˣ with respect to x is eˣ + C.',
    solution_short_hi: 'eˣ का समाकलन eˣ + C होता है।',
    exam_year: '2020A'
  },
  {
    id: 305,
    subject: 'Maths',
    chapter_name_en: 'Vector Algebra',
    chapter_name_hi: 'सदिश बीजगणित',
    question_text_en: 'The dot product of perpendicular vectors (a⃗ ⊥ b⃗) is always:',
    question_text_hi: 'दो परस्पर लंबवत सदिशों का अदिश गुणनफल (a⃗ · b⃗) होता है:',
    option_a_en: '0',
    option_a_hi: '0',
    option_b_en: '1',
    option_b_hi: '1',
    option_c_en: '|a⃗||b⃗|',
    option_c_hi: '|a⃗||b⃗|',
    option_d_en: '-1',
    option_d_hi: '-1',
    correct_option: 'A',
    solution_short_en: 'a⃗ · b⃗ = |a||b| cos(90°) = 0.',
    solution_short_hi: 'क्योंकि cos(90°) = 0, अतः लंबवत सदिशों का डॉट गुणनफल शून्य होता है।',
    exam_year: '2024A'
  },

  // --- BIOLOGY ---
  {
    id: 401,
    subject: 'Biology',
    chapter_name_en: 'Sexual Reproduction in Flowering Plants',
    chapter_name_hi: 'पुष्पी पादपों में लैंगिक प्रजनन',
    question_text_en: 'Triple fusion in angiosperms results in the formation of:',
    question_text_hi: 'आवृतबीजी पौधों में त्रिसंलयन के फलस्वरूप किसका निर्माण होता है?',
    option_a_en: 'Endosperm',
    option_a_hi: 'भ्रूणपोष',
    option_b_en: 'Embryo',
    option_b_hi: 'भ्रूण',
    option_c_en: 'Zygote',
    option_c_hi: 'युग्मनज',
    option_d_en: 'Seed coat',
    option_d_hi: 'बीजचोल',
    correct_option: 'A',
    solution_short_en: 'One sperm nucleus fuses with two polar nuclei to form triploid (3n) primary endosperm nucleus.',
    solution_short_hi: 'त्रिसंलयन से त्रिगुणित (3n) प्राथमिक भ्रूणपोष केंद्रक बनता है जो भ्रूणपोष का निर्माण करता है।',
    exam_year: '2021A'
  },
  {
    id: 402,
    subject: 'Biology',
    chapter_name_en: 'Human Reproduction',
    chapter_name_hi: 'मानव जनन',
    question_text_en: 'In human females, fertilization normally takes place in the:',
    question_text_hi: 'मानव मादा में निषेचन सामान्यतः कहाँ होता है?',
    option_a_en: 'Fallopian tube (Ampulla)',
    option_a_hi: 'फैलोपियन नलिका (एम्पुला)',
    option_b_en: 'Uterus',
    option_b_hi: 'गर्भाशय',
    option_c_en: 'Ovary',
    option_c_hi: 'अंडाशय',
    option_d_en: 'Vagina',
    option_d_hi: 'योनि',
    correct_option: 'A',
    solution_short_en: 'Fertilization occurs at the ampullary region of the fallopian tube.',
    solution_short_hi: 'निषेचन फैलोपियन नलिका के एम्पुला (तुंबिका) भाग में होता है।',
    exam_year: '2022A'
  },
  {
    id: 403,
    subject: 'Biology',
    chapter_name_en: 'Principles of Inheritance and Variation',
    chapter_name_hi: 'वंशागति तथा विविधता के सिद्धांत',
    question_text_en: 'The monohybrid phenotypic ratio according to Mendel’s law is:',
    question_text_hi: 'मेंडल के एकसंकर संकरण का दृश्यरूप (फीनोटाइपिक) अनुपात होता है:',
    option_a_en: '3 : 1',
    option_a_hi: '3 : 1',
    option_b_en: '1 : 2 : 1',
    option_b_hi: '1 : 2 : 1',
    option_c_en: '9 : 3 : 3 : 1',
    option_c_hi: '9 : 3 : 3 : 1',
    option_d_en: '2 : 1',
    option_d_hi: '2 : 1',
    correct_option: 'A',
    solution_short_en: 'Phenotypic ratio is 3:1 (Tall:Dwarf). Genotypic ratio is 1:2:1 (TT:Tt:tt).',
    solution_short_hi: 'एकसंकर दृश्यरूप अनुपात 3:1 तथा जीनोटाइपिक अनुपात 1:2:1 होता है।',
    exam_year: '2020A'
  },

  // --- HINDI ---
  {
    id: 501,
    subject: 'Hindi',
    chapter_name_en: 'Baatchit',
    chapter_name_hi: 'बातचीत (बालकृष्ण भट्ट)',
    question_text_en: 'Who is the author of the essay "Baatchit"?',
    question_text_hi: '"बातचीत" शीर्षक निबंध के निबंधकार कौन हैं?',
    option_a_en: 'Balkrishna Bhatt',
    option_a_hi: 'बालकृष्ण भट्ट',
    option_b_en: 'Chandradhar Sharma Guleri',
    option_b_hi: 'चंद्रधर शर्मा गुलेरी',
    option_c_en: 'Ramdhari Singh Dinkar',
    option_c_hi: 'रामधारी सिंह दिनकर',
    option_d_en: 'Jayprakash Narayan',
    option_d_hi: 'जयप्रकाश नारायण',
    correct_option: 'A',
    solution_short_en: 'The essay "Baatchit" is written by Balkrishna Bhatt, a pioneer of modern Hindi prose.',
    solution_short_hi: '"बातचीत" निबंध के रचनाकार भारतेंदु युग के प्रमुख साहित्यकार बालकृष्ण भट्ट हैं।',
    exam_year: '2022A'
  },
  {
    id: 502,
    subject: 'Hindi',
    chapter_name_en: 'Usne Kaha Tha',
    chapter_name_hi: 'उसने कहा था (चन्द्रधर शर्मा गुलेरी)',
    question_text_en: 'Who is the central character of the story "Usne Kaha Tha"?',
    question_text_hi: '"उसने कहा था" कहानी के मुख्य पात्र (नायक) कौन हैं?',
    option_a_en: 'Lahna Singh',
    option_a_hi: 'लहना सिंह',
    option_b_en: 'Bodh Singh',
    option_b_hi: 'बोधा सिंह',
    option_c_en: 'Hazara Singh',
    option_c_hi: 'हजारा सिंह',
    option_d_en: 'Wazira Singh',
    option_d_hi: 'वजीरा सिंह',
    correct_option: 'A',
    solution_short_en: 'Lahna Singh is the noble, dutiful soldier protagonist in "Usne Kaha Tha".',
    solution_short_hi: 'चंद्रधर शर्मा गुलेरी की अमर कहानी "उसने कहा था" के मुख्य पात्र जमादार लहना सिंह हैं।',
    exam_year: '2023A'
  },

  // --- ENGLISH ---
  {
    id: 601,
    subject: 'English',
    chapter_name_en: 'Indian Civilization and Culture',
    chapter_name_hi: 'Indian Civilization and Culture (M. Gandhi)',
    question_text_en: 'Who wrote the piece "Indian Civilization and Culture"?',
    question_text_hi: '"Indian Civilization and Culture" के लेखक कौन हैं?',
    option_a_en: 'Mahatma Gandhi',
    option_a_hi: 'महात्मा गांधी',
    option_b_en: 'Dr. Zakir Hussain',
    option_b_hi: 'डॉ. जाकिर हुसैन',
    option_c_en: 'Manohar Malgonkar',
    option_c_hi: 'मनोहर मालगांवकर',
    option_d_en: 'Martin Luther King Jr.',
    option_d_hi: 'मार्टिन लूथर किंग जूनियर',
    correct_option: 'A',
    solution_short_en: '"Indian Civilization and Culture" is an excerpt from Mahatma Gandhi’s writing in Young India.',
    solution_short_hi: '"Indian Civilization and Culture" महात्मा गांधी द्वारा लिखित एक प्रसिद्ध निबंध है।',
    exam_year: '2022A'
  },
  {
    id: 602,
    subject: 'English',
    chapter_name_en: 'Bharat is My Home',
    chapter_name_hi: 'Bharat is My Home (Dr. Zakir Hussain)',
    question_text_en: 'Dr. Zakir Hussain took the oath as the President of India in which year?',
    question_text_hi: 'डॉ. जाकिर हुसैन ने किस वर्ष भारत के राष्ट्रपति के रूप में शपथ ली थी?',
    option_a_en: '1967',
    option_a_hi: '1967',
    option_b_en: '1962',
    option_b_hi: '1962',
    option_c_en: '1971',
    option_c_hi: '1971',
    option_d_en: '1950',
    option_d_hi: '1950',
    correct_option: 'A',
    solution_short_en: 'Dr. Zakir Hussain became President in 1967 and gave his historic speech "Bharat is My Home".',
    solution_short_hi: 'डॉ. जाकिर हुसैन ने 1967 में राष्ट्रपति पद की शपथ ली थी।',
    exam_year: '2023A'
  }
];

export const COMPREHENSIVE_PYQS: PYQQuestion[] = [
  {
    id: 701,
    subject: 'Physics',
    chapter_name_en: 'Electric Charges and Fields',
    chapter_name_hi: 'वैद्युत आवेश तथा क्षेत्र',
    question_text_en: 'What is the dimensional formula of electric charge?',
    question_text_hi: 'विद्युत आवेश का विमीय सूत्र क्या होता है?',
    option_a_en: '[A T]',
    option_a_hi: '[A T]',
    option_b_en: '[A⁻¹ T]',
    option_b_hi: '[A⁻¹ T]',
    option_c_en: '[A T⁻¹]',
    option_c_hi: '[A T⁻¹]',
    option_d_en: '[A T²]',
    option_d_hi: '[A T²]',
    correct_option: 'A',
    solution_short_en: 'Q = I * t = [A] * [T] = [A T].',
    solution_short_hi: 'Q = I * t, अतः आवेश की विमा [A T] होती है।',
    exam_year: '2024',
    question_type: 'objective'
  },
  {
    id: 702,
    subject: 'Physics',
    chapter_name_en: 'Electric Charges and Fields',
    chapter_name_hi: 'वैद्युत आवेश तथा क्षेत्र',
    question_text_en: 'State Coulomb’s law of electrostatic force between two point charges.',
    question_text_hi: 'दो बिंदु आवेशों के बीच लगने वाले स्थिरविद्युत बल के लिए कूलॉम का नियम लिखें।',
    option_a_en: null,
    option_a_hi: null,
    option_b_en: null,
    option_b_hi: null,
    option_c_en: null,
    option_c_hi: null,
    option_d_en: null,
    option_d_hi: null,
    correct_option: 'A',
    solution_short_en: 'F = (1/4πε₀) * (|q₁q₂| / r²).',
    solution_short_hi: 'F = (1/4πε₀) * (|q₁q₂| / r²).',
    answer_text_en: 'Coulomb’s Law states that the electrostatic force between two stationary point charges is directly proportional to the product of the magnitudes of charges and inversely proportional to the square of the distance between them. F = (1/4πε₀)(q₁q₂/r²).',
    answer_text_hi: 'कूलॉम के नियमानुसार, दो स्थिर बिंदु आवेशों के बीच लगने वाला आकर्षण या प्रतिकर्षण बल दोनों आवेशों के परिमाण के गुणनफल के समानुपाती तथा उनके बीच की दूरी के वर्ग के व्युत्क्रमानुपाती होता है। सूत्र: F = (1/4πε₀) · (|q₁q₂| / r²).',
    marks: 2,
    exam_year: '2024',
    question_type: 'subjective'
  }
];
