import React, { useState, useEffect } from 'react';

export interface SmartThumbnailProps {
  videoId: string;
  title?: string;
  duration?: string;
  className?: string;
  imgClassName?: string;
  badgeClassName?: string;
  showPlayIcon?: boolean;
  priority?: boolean;
}

// Direct YouTube CDN URL hierarchy for maximum 1080p/HD fidelity with zero API quota consumption
const RESOLUTION_URLS = [
  // 1. Primary: Direct YouTube WebP Full HD (Fastest load + crystal-clear 1080p)
  (id: string) => `https://i.ytimg.com/vi_webp/${id}/maxresdefault.webp`,
  // 2. Fallback 1: Standard JPG Full HD (if WebP is unsupported or unavailable)
  (id: string) => `https://i.ytimg.com/vi/${id}/maxresdefault.jpg`,
  // 3. Fallback 2: Standard Definition (if maxres is not generated by YouTube)
  (id: string) => `https://i.ytimg.com/vi/${id}/sddefault.jpg`,
  // 4. Final Fallback: High Quality (4:3 ratio, cropped cleanly by object-cover)
  (id: string) => `https://i.ytimg.com/vi/${id}/hqdefault.jpg`
];

/**
 * SmartThumbnail: High-performance, zero-quota 1080p HD YouTube thumbnail component.
 * Features YouTube's exact light-grey skeleton color, zero spinner, dummy 120x90 check,
 * and official YouTube mobile duration badge styling.
 */
export const SmartThumbnail: React.FC<SmartThumbnailProps> = ({
  videoId,
  title = 'Video thumbnail',
  duration,
  className = '',
  imgClassName = '',
  badgeClassName = '',
  showPlayIcon = false,
  priority = false
}) => {
  const [fallbackIndex, setFallbackIndex] = useState(0);
  const [isLoaded, setIsLoaded] = useState(false);

  // Reset fallback index whenever the videoId changes
  useEffect(() => {
    setFallbackIndex(0);
    setIsLoaded(false);
  }, [videoId]);

  const currentUrl = videoId
    ? RESOLUTION_URLS[fallbackIndex](videoId)
    : 'https://via.placeholder.com/640x360?text=No+Thumbnail';

  const handleNextFallback = () => {
    setIsLoaded(false);
    if (fallbackIndex < RESOLUTION_URLS.length - 1) {
      setFallbackIndex(prev => prev + 1);
    }
  };

  const handleImageLoad = (e: React.SyntheticEvent<HTMLImageElement, Event>) => {
    const img = e.currentTarget;
    // YouTube returns a 120x90 placeholder when maxres/sd thumbnail is missing
    if (img.naturalWidth === 120 || (img.naturalWidth === 120 && img.naturalHeight === 90)) {
      setIsLoaded(false);
      handleNextFallback();
    } else if (img.naturalWidth > 120) {
      setIsLoaded(true);
    }
  };

  const handleImageError = () => {
    setIsLoaded(false);
    handleNextFallback();
  };

  return (
    <div
      className={`relative w-full aspect-video bg-[#e5e5e5] dark:bg-neutral-800 ${
        !isLoaded ? 'animate-pulse' : ''
      } rounded-xl sm:rounded-2xl overflow-hidden select-none ${className}`}
    >
      {/* Main Thumbnail Image - invisible while loading to avoid any dummy image flash */}
      <img
        src={currentUrl}
        alt={title}
        loading={priority ? 'eager' : 'lazy'}
        onLoad={handleImageLoad}
        onError={handleImageError}
        className={`w-full h-full object-cover ${
          isLoaded ? 'opacity-100 transition-opacity duration-200' : 'opacity-0'
        } ${imgClassName}`}
      />

      {/* Optional Play Icon Overlay */}
      {showPlayIcon && isLoaded && (
        <div className="absolute inset-0 flex items-center justify-center pointer-events-none z-10 bg-black/10 group-hover:bg-black/25 transition-colors">
          <div className="w-10 h-10 rounded-full bg-red-600 text-white flex items-center justify-center shadow-lg transform group-hover:scale-110 transition-transform">
            <svg
              className="w-4 h-4 fill-current ml-0.5"
              viewBox="0 0 24 24"
            >
              <path d="M8 5v14l11-7z" />
            </svg>
          </div>
        </div>
      )}

      {/* Duration Badge formatted exactly like official YouTube mobile */}
      {duration && isLoaded && (
        <span
          className={`absolute bottom-2 right-2 bg-black/80 text-white text-[12px] font-medium px-1.5 py-0.5 rounded-[4px] leading-none pointer-events-none z-10 ${badgeClassName}`}
        >
          {duration}
        </span>
      )}
    </div>
  );
};
